version: "2"
services:
  # for development purposes
  dev:
    build:
      context: .
      target: production
    volumes:
        - ./:/code
        - ./data:/data
    environment:
      - KBC_DATADIR=./data
  test:
    # Use to run ruff and pytest checks
    build:
      context: .
      target: test
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
    command:
      - /bin/sh
      - /code/scripts/build_n_test.sh